projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - service
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
        region: us-east-1
        apiId: vz6yhileqzamvm6t7fzr2gsmfa
        frontend: javascript
        framework: react
        maxDepth: 3
